### ISSUE TITLE
create categories 

### ISSUE THREAD

**Issue by mekhaleganesh** [Sagar2693/Team5_COMP313-001_SoftwareDevelopment2#20]
#12

**Comment by hlac** [comment]
Too small to be called a Task.


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by zeal1010** [comment]
As informed earlier, it is too small to be called a Task. Therefore a single task is created under the user story. Could not delete the task earlier due to access issues.Therefore had to close explicitly. My apologizes for not specifying the reason earlier.

Thanks,
Zeal Shukla
zealshukla@gmail.com

**Comment by hlac** [comment]
INVALID.
