### ISSUE TITLE
show list of categorized item

### ISSUE THREAD

**Issue by mekhaleganesh** [Sagar2693/Team5_COMP313-001_SoftwareDevelopment2#21]
#12

**Comment by hlac** [comment]
Is there enough work in this issue to call it a Task?  A Task should be represent a unit of work that is too small to be a story but big enough to take about 3 ideal developer hours to implement.

**Comment by zeal1010** [comment]
As informed earlier, it is too small to be called a Task. Therefore a single task is created under the user story. Could not delete the task earlier due to access issues.Therefore had to close explicitly. My apologizes for not specifying the reason earlier.

Thanks,
Zeal Shukla
zealshukla@gmail.com
