### ISSUE TITLE
Create a UI to display a list of items to select category

### ISSUE THREAD

**Issue by zeal1010** [Sagar2693/Team5_COMP313-001_SoftwareDevelopment2#22]

**Comment by hlac** [comment]
Let's stick with the term "UI" instead of "Activity" so that it would be a
valid unit of work.  "Activity" is too specific and most likely too small
to be its own Task.


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by zeal1010** [comment]
updated

**Comment by mekhaleganesh** [comment]
Duplicate task - INVALID
