### ISSUE TITLE
Update the cart before final order placement

### ISSUE THREAD

**Issue by zeal1010** [Sagar2693/Team5_COMP313-001_SoftwareDevelopment2#24]

**Comment by hlac** [comment]
I don't understand what this issue is for.  A two word sentence doesn't say
much.  Please use proper language (updation).


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by zeal1010** [comment]
Changed.

**Comment by hlac** [comment]
What did I say about multiple assignee per issue?  And if it is assigned to someone, why is it not allocated to a Milestone?

**Comment by mekhaleganesh** [comment]
Duplicate Task - INVALID
